Resources:
  MYSQLRDS:
    Type: "AWS::RDS::DBInstance"
    Properties:
      AllocatedStorage: 20
      AvailabilityZone: us-east-2b
      DBInstanceClass: db.t2.micro
      DBInstanceIdentifier: shariqdatabase1
      DBName: shariqdatabase
      DBSubnetGroupName: 
        Fn::ImportValue: shariqstack-DB-Subnet
      Engine: MySQL
      MasterUsername: shariq
      MasterUserPassword: shariq12
      MultiAZ: false
      Port: 3306
      PubliclyAccessible: false
      Tags:
        - Key: Name
          Value: Shariq-Cloud-RDS-Postgres
      VPCSecurityGroups:
        - Fn::ImportValue: shariqstack-DbSecurityGroup