---
# tasks file for db
- name: get the variables
  include_vars: ../../../group_vars/vault.yml    

- name: Install MySQL 5.7 repo
  yum: name=http://dev.mysql.com/get/mysql57-community-release-el7-8.noarch.rpm state=present

- name: Install MySQL 5.7
  yum:
    name: ['mysql-community-devel*', 'mysql-community-server*', 'MySQL-python']
    state: present

- name: Start the MySQL service
  service: name=mysqld state=started enabled=true

- name: Change mysql root password and keep track in 
  shell: |
    password_match=`awk '/A temporary password is generated for/ {a=$0} END{ print a }' /var/log/mysqld.log | awk '{print $(NF)}'`
    echo $password_match
    mysql -uroot -p$password_match --connect-expired-password -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ db_pass }}'; flush privileges; "
    mysql -uroot -p$password_match --connect-expired-password -e "CREATE USER 'root'@'%' IDENTIFIED BY '{{ db_pass }}'; flush privileges; "
    mysql -uroot -p$password_match --connect-expired-password -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%'WITH GRANT OPTION; flush privileges; "
    echo "[client]"
    user=root
    password={{ db_pass }} > /root/.my.cnf
  args:
    creates: /root/.my.cnf
  register: change_temp_pass
  notify: restart mysqld

- meta: flush_handlers
